franziska:
  token: <discord-bot-token>
  status: <presence-message>
  owner: <bot-owner-snowflake>
mongo:
  host: <mongo-host>
  port: <mongo-port>
  database: <mongo-database>
  username: <mongo-username>
  password: <mongo-password>